Тебя взломали
#include <iostream>
#include <string>
using namespace std; 
int main() 
{ 
int a = 52; 
cout << "a= " << a << endl; 
int b = -42; 
cout << "b = " << b << endl; 
int c = -5; 
cout << "c = " << c << endl; 
int d = -5; 
cout << "d = " << d << endl; 
int e = -1488; 
cout << "e = " << e << endl; 
short chislo2 = 11; 
cout << "chislo2 = " << chislo2 << endl; 
short chislo3 = 22; 
cout << "chislo3 = " << chislo3 << endl; 
short chislo4 = 33; 
cout << "chislo4 = " << chislo4 << endl; 
short chislo5 = 66; 
cout << "chislo5 = " << chislo5 << endl; 
short chislo6 = 77; 
cout << "chislo6 = " << chislo6 << endl; 
float aa1 = 12; 
cout << " aa1 = " << aa1 << endl; 
float aa2 = 11; 
cout << " aa2 = " << aa2 << endl; 
float aa3 = 22; 
cout << " aa3 = " << aa3 << endl; 
float aa4 = 44; 
cout << " aa4 = " << aa4 << endl; 
float aa5 = 55; 
cout << " aa5 = " << aa5 << endl; 
double a10 = 35; 
cout << " a10 = " << a10 << endl; 
double a11 = 35; 
cout << " a11 = " << a11 << endl; 
double a12 = 35; 
cout << " a12 = " << a12 << endl; 
double a13 = 35; 
cout << " a13 = " << a13 << endl; 
double a14 = 35; 
cout << " a14 = " << a14 << endl; 
char b1 = '1'; 
cout << " b1 = " << b1 << endl; 
char b2 = '2'; 
cout << " b2 = " << b2 << endl; 
char b3 = '3'; 
cout << " b3 = " << b3 << endl; 
char b4 = '4'; 
cout << " b4 = " << b4 << endl; 
char b5 = '5'; 
cout << " b5 = " << b5 << endl; 
bool MAMA = 109; 
cout << " MAMA = " << MAMA << endl; 
bool DAD = 103; 
cout << " DAD = " << DAD << endl; 
bool LALO = 104; 
cout << " LALO = " << LALO << endl; 
bool FAFA = 105; 
cout << " FAFA = " << FAFA << endl; 
bool XZXZXD = 110; 
cout << " XZXZXD = " << XZXZXD << endl; 
string MOSCOW = "CITY"; 
cout << " MOSCOW = " << MOSCOW << endl; 
string VORONEZH = "LOVE"; 
cout << " VORONEZH = " << VORONEZH << endl; 
string AMERICAN = "PINDOS"; 
cout << " AMERICAN = " << AMERICAN << endl; 
string UKRANIAN = "XOXOL"; 
cout << " UKRANIAN = " << UKRANIAN << endl; 
string BELARUSIAN = "BULBA"; 
cout << " BELARUSIAN = " << BELARUSIAN << endl;
}
